import { useState, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import Image from 'next/image'

const defaultEndPoint = "https://rickandmortyapi.com/api/character/";

export async function getServerSideProps() {
  const res = await fetch(defaultEndPoint)
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

export default function Home({ data }) {
  console.log(data);
  const [searchName, setSearchName] = useState('')
  const { info, results: defaultResults = [] } = data
  const [results, updateResults] = useState(defaultResults)
  const [page, updatePage] = useState({
    ...info, current: defaultEndPoint
  })
  const { current } = page
  useEffect(() => {
    if (current === defaultEndPoint) return
    async function request() {
      const res = await fetch(current)
      const nextData = await res.json()
      updatePage({
        current,
        ...nextData.info
      })

      if (!nextData.info?.prev) {
        updateResults(nextData.results)
        return
      }
      updateResults(prev => {
        return [
          ...prev,
          ...nextData.results
        ]
      })
    }
    request()
  }, [current]);

  const handleLoadMore = () => {
    updatePage(prev => {
      return {
        ...prev,
        current: page?.next
      }
    })
  }
  const handleSearch = () => {
    const endPoint = `https://rickandmortyapi.com/api/character/?name=${searchName}`;
    updatePage({
      current: endPoint
    })
  }
  return (
    <div >
      <Head>
        <title>Rick and Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section className={styles.section}>
          <div>

            <img className={styles.logo} src="logo.png" />

            <div className={styles.form}>
              <input className={styles.input} type="search" name='query' placeholder='Find Character' onChange={(e) => {
                setSearchName(e.target.value)
              }} />
              <button className={styles.button} onClick={handleSearch}>Search</button>
            </div>
          </div>
        </section>

        <ul className={styles.content}>
          {results.map(char => {
            const { id, name, image, status } = char
            return (
              <li className={styles.listItem} key={id}>
                <Link href={`character/${id}`}  >
                  <a>
                    <img src={image} />
                    <div className={styles.charInformation}>
                      <h2>{name}</h2>
                      <p><span>Status:</span> {status}</p>

                    </div>

                  </a>
                </Link>
              </li>
            )
          })}
        </ul>
        <button className={styles.loadMore} onClick={handleLoadMore}>Load more</button>




        <footer className={styles.footer}>
          Fun Fun Project
        </footer>


      </main>

    </div >
  )
}
